name: VyOS LTS Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container: 
      # For VyOS 1.2 (crux) use vyos/vyos-build:crux
      # For VyOS 1.3 (equuleus) use vyos/vyos-build:equuleus
      # For our VyOS rolling release you should use vyos/vyos-build which will always refer to the latest image.
      # Ref: https://docs.vyos.io/en/latest/contributing/build-vyos.html#build
      image: vyos/vyos-build:crux

    steps:
    - name: git clone vyos-build
      run: |
        set -eux
        
        git clone -b crux --single-branch https://github.com/vyos/vyos-build

    - name: configure
      working-directory: vyos-build
      run: |
        set -eux
        
        pwd
        ls -lah
        ./configure \
          --architecture amd64 \
          --build-by naa0yama@aoya6i.com \
          --build-type release \
          --version 1.2.4
